dist: xenial # Ubuntu 16.04
language: bash
before_install:
  - wget https://releases.hashicorp.com/terraform/0.13.2/terraform_0.13.2_linux_amd64.zip
  - unzip terraform_0.13.2_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_0.13.2_linux_amd64.zip

jobs:
  include:
    - stage: Plan
      script:
        - terraform init
        - terraform plan -out=myplan
        - terraform show myplan
